apiVersion: v1
kind: Service
metadata:
  name: puhu-tv
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: puhu-tv
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: puhu-tv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: puhu-tv
  template:
    metadata:
      labels:
        app: puhu-tv
    spec:
      containers:
        - name: puhu-tv
          image: puhutv/puhu-tv
          resources:
            requests:
              memory: "256Mi"
              cpu: "300m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "80"